name: "Build"
run-name: Build - ${{ github.repository }}

on:
  workflow_call:
  workflow_dispatch:
#   push:
          
permissions:
  id-token: write
  actions: read
  contents: read
  packages: read
  security-events: write

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        run: echo "setup"

  test:
    needs: 
      - build
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        run: echo "test"



