name: Build And Deploy Dev
run-name: Build And Deploy Dev - ${{ github.repository }}

on:
  push:
  workflow_dispatch:
    
permissions:
  id-token: write
  actions: read
  contents: read
  packages: read
  security-events: write
 

jobs:

  semantic-release:
    uses:  ./.github/workflows/semantic-release.yml
    permissions:
      actions: read
      contents: write
      issues: write
    secrets: inherit    
    needs:
      - build
      
  build:
    uses:  ./.github/workflows/build.yml
    permissions:
      id-token: write
      actions: read
      contents: read
      packages: read
      security-events: write
    secrets: inherit

  deploy:
    if: github.ref_name == 'main'
    uses:  ./.github/workflows/deploy.yml
    needs:
      - build
    permissions:
      id-token: write
      actions: read
      contents: read
      packages: read
      security-events: write
    secrets: inherit