name: "Build"
run-name: Build - ${{ github.repository }}

on:
  workflow_call:
  workflow_dispatch:
#   push:
          
permissions:
  id-token: write
  actions: read
  contents: read
  packages: read
  security-events: write

jobs:

  build:
    runs-on:
      - codebuild-yrdy-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - name: Setup Build
        run: echo "setup"

      - name: Get runner environment information
        run: |
          echo "Runner Environment Information:"
          cat /etc/os-release
        continue-on-error: true        

  test:
    needs: 
      - build
    runs-on:
      - codebuild-yrdy-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - name: Setup Test
        run: echo "test"

      - name: Get runner environment information
        run: |
          echo "Runner Environment Information:"
          cat /etc/os-release
        continue-on-error: true