name: Codebuild Runner
on: 
  push:
  workflow_call:
  workflow_dispatch:

jobs:

  include-codebuild-build:
    uses:  ./.github/workflows/codebuild-build.yml  

  codebuild-set-output:
    runs-on:
      - codebuild-yrdy-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - name: Set output in job1
        id: set-output-job
        run: |
          echo "::set-output name=codebuild-output::Codebuild Build Output from Job 1"
    outputs:
      codebuild-output: ${{ steps.set-output-job.outputs.codebuild-output }}

  job2:
    runs-on: ubuntu-latest
    needs: codebuild-set-output
    steps:
      - name: Print output from Job 1
        run: |
          echo "Output from Job 1: ${{ needs.codebuild-set-output.outputs.codebuild-output }}"      

  github-set-output:
    runs-on:
      - ubuntu-latest
    steps:
      - name: Set output in job1
        id: set-output-job
        run: |
          echo "my-output=Github Build Output from Job 1" >> $GITHUB_ENV

    outputs:
      my-output: ${{ steps.set-output-job.outputs.my-output }}

  codebuild-environment:
    needs:
      - codebuild-set-output
      - github-set-output
    runs-on:
      - codebuild-yrdy-${{ github.run_id }}-${{ github.run_attempt }}
    steps:

      # - name: Checkout code
      #   uses: actions/checkout@v2

      - name: local folders
        run: |
          pwd
          ls -al

      - name: Read environment variables
        run: |
          echo "Environment Variables:"
          for key in $(env -i); do
            echo "$key"
          done

      - name: Write environment variables
        run: |
          echo "Writing environment variables..."
          export MY_VAR=Hello World
          echo $MY_VAR

  codebuild-checkout-repository:
    runs-on:
      - codebuild-yrdy-${{ github.run_id }}-${{ github.run_attempt }}
    needs:
      - codebuild-set-output
      - github-set-output      
    steps:
      - name: Echo codebuid job output
        run: |
          echo "${{ needs.codebuild-set-output.outputs.my-output }}"
      - name: Echo github job output
        run: |
          echo "${{ needs.github-set-output.outputs.my-output }}"

      - name: Checkout repository
        uses: actions/checkout@v2
      - name: List Files
        run: |
          ls -al
          find .

  codebuild-setup-node:
    runs-on:
      - codebuild-yrdy-${{ github.run_id }}-${{ github.run_attempt }}
    needs:
      - codebuild-set-output
      - github-set-output      
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Check version
        run: |
          node --version

  codebuild-setup-python:
    runs-on:
      - codebuild-yrdy-${{ github.run_id }}-${{ github.run_attempt }}
    needs:
      - codebuild-set-output
      - github-set-output      
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11.0'
      - name: Check version
        run: |
          python --version

  codebuild-upload-artifact:
    runs-on:
      - codebuild-yrdy-${{ github.run_id }}-${{ github.run_attempt }}
    needs:
      - codebuild-set-output
      - github-set-output      
    steps:
      - name: create-artifact
        run: |
          echo aaa > build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: ./build

  codebuild-download-artifact:
    runs-on:
      - codebuild-yrdy-${{ github.run_id }}-${{ github.run_attempt }}
    needs:
      - codebuild-set-output
      - github-set-output  
      - codebuild-upload-artifact
    
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
      - name: List files
        run: |
          ls -al
          find .

  codebuild-github-script:
    runs-on:
      - codebuild-yrdy-${{ github.run_id }}-${{ github.run_attempt }}
    needs:
      - codebuild-set-output
      - github-set-output      
    steps:
      - name: Print issue title
        uses: actions/github-script@v6
        with:
          script: |
            const issue_title = 'Automated Issue';
            console.log('Issue title:', issue_title);

  codebuild-github-add-label:
    runs-on:
      - codebuild-yrdy-${{ github.run_id }}-${{ github.run_attempt }}
    needs:
      - codebuild-set-output
      - github-set-output      
    steps:
        - name: Label PRs based on their content
          uses: actions/labeler@v3
          with:
            repo-token: ${{ secrets.GH_TOKEN }}
