name: "Action AWS Codebuild Runner"
run-name: Action AWS Codebuild Runner - ${{ github.repository }}

on:
  workflow_call:
  workflow_dispatch:
#   push:
          
permissions:
  id-token: write
  actions: read
  contents: read
  packages: read
  security-events: write

jobs:

  aws-code-build-runner-build:
    runs-on:
      - codebuild-yrdy-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - name: Setup Build
        run: echo "setup"

      - name: Get runner environment information
        run: |
          echo "Runner Environment Information:"
          cat /etc/os-release
        continue-on-error: true        

  github-runner-test:
    needs: 
      - aws-code-build-runner-build
    runs-on:
      - ubuntu-latest
    steps:
      - name: Setup Test
        run: echo "test"

      - name: Get runner environment information
        run: |
          echo "Runner Environment Information:"
          cat /etc/os-release
        continue-on-error: true

  aws-code-build-runner-validate:
    runs-on:
      - codebuild-yrdy-${{ github.run_id }}-${{ github.run_attempt }}
    needs:
      - github-runner-test
    steps:
      - name: Setup Build
        run: echo "setup"

      - name: Get runner environment information
        run: |
          echo "Runner Environment Information:"
          cat /etc/os-release
        continue-on-error: true   