name: "Action AWS Codebuild Runner"
run-name: Action AWS Codebuild Runner - ${{ github.repository }}

on:
  workflow_call:
  workflow_dispatch:
#   push:
          
permissions:
  id-token: write
  actions: read
  contents: read
  packages: read
  security-events: write

jobs:
  codebuild-build:
    runs-on:
      - codebuild-yrdy-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - name: Setup Build
        run: echo "setup"

      - name: Get runner environment information
        run: |
          echo "Runner Environment Information:"
          cat /etc/os-release
        continue-on-error: true        

      - name: Set output in job1
        id: set-output-job1
        run: |
          echo "my-output=Hello from Job 1" >> $GITHUB_ENV

    outputs:
      my-output: ${{ steps.set-output-job1.outputs.my-output }}

  github-runner-build:
    needs: 
      - codebuild-build
    runs-on:
      - ubuntu-latest
    steps:
      - name: Setup Test
        run: echo "test"

      - name: Get runner environment information
        run: |
          echo "Runner Environment Information:"
          cat /etc/os-release
        continue-on-error: true
      
      - name: Set output in job1
        id: set-output-job1
        run: |
          echo "my-output=Hello from Job 1" >> $GITHUB_ENV

    outputs:
      my-output: ${{ steps.set-output-job1.outputs.my-output }}

  codebuild-validate:
    runs-on:
      - codebuild-yrdy-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - name: Setup Build
        run: echo "setup"

      - name: Get runner environment information
        run: |
          echo "Runner Environment Information:"
          cat /etc/os-release
        continue-on-error: true   