name: "Deploy"
run-name: Deploy - ${{ github.repository }}

on:
  workflow_call:
  workflow_dispatch:
#   push:
          
permissions:
  id-token: write
  actions: read
  contents: read
  packages: read
  security-events: write

jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: echo "deploy"
