name: Deploy Dev
run-name: Deploy Dev - ${{ github.repository }}

on:
  workflow_dispatch:
    
permissions:
  id-token: write
  actions: read
  contents: read
  packages: read
  security-events: write
 

jobs:

  deploy:
    if: github.ref_name == 'main'
    uses:  ./.github/workflows/deploy.yml
    permissions:
      id-token: write
      actions: read
      contents: read
      packages: read
      security-events: write
    secrets: inherit