name: Pipeline
on: 
  push:
  workflow_call:
jobs:

  codebuild:
    uses: ./.github/workflows/codebuild-runner.yaml

  github:
    uses: ./.github/workflows/github-runner.yaml

  codebuild2:
    needs:
      - codebuild
      - github
    uses: ./.github/workflows/codebuild-runner.yaml

  github2:
    needs:
      - github2
    uses: ./.github/workflows/github-runner.yaml    
