name: Semantic Release
run-name: Semantic Release

on:
  workflow_call:

  # workflow_dispatch:
  # push:

permissions:
  actions: read
  contents: write
  issues: write

jobs:
  version:
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          depth: 1

      # Step 2: Set up Node.js to use semantic-release for versioning
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install semantic-release @semantic-release/changelog @semantic-release/commit-analyzer @semantic-release/git @semantic-release/github @semantic-release/release-notes-generator

      - name: Semantic Version Tag
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
        run: npx semantic-release --plugins=@semantic-release/commit-analyzer,@semantic-release/release-notes-generator,@semantic-release/changelog,@semantic-release/git


